export const DISPLAY_MODE = 'DISPLAY_MODE';
export const EDIT_MODE = 'EDIT_MODE';

export const FILE_STATUS_LOADING = 'FILE_STATUS_LOADING';
export const FILE_STATUS_COMPLETE = 'FILE_STATUS_COMPLETE';
export const FILE_STATUS_ERROR = 'FILE_STATUS_ERROR';
export const FILE_STATUS_TIMEOUT = 'FILE_STATUS_TIMEOUT';
